### Numpy Task

In [4]:
import numpy as np

# 1~10까지의 요소를 ndarray에 담는다.
ndarray1 = np.arange(start=1, stop=11)
print(ndarray1)
print("=" * 30)

# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5 ,4, 3, 2, 1이다.
ndarray1 = np.arange(start=6, stop=0, step=-1)
ndarray2 = ndarray1.reshape((3, 2))
print(ndarray2)
print("=" * 30)

# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
ndarray1 = np.arange(start=10, stop=3, step=-2)
ndarray2 = ndarray1.reshape((4, 1))
print(ndarray2)
print("=" * 30)

# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray1 = ndarray1 + 5

print(ndarray1)
print("=" * 30)

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
ndarray1 = np.zeros((10,), dtype=np.int32)
print(ndarray1)
print("=" * 30)

# axis 0이 3, axis 1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray1 = np.arange(12)
ndarray2 = ndarray1.reshape((3, -1))
ndarray2 = np.ones((3, 4))
print(ndarray2)
print("=" * 30)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(stop=5)
print(ndarray1)


[ 1  2  3  4  5  6  7  8  9 10]
[[6 5]
 [4 3]
 [2 1]]
[[10]
 [ 8]
 [ 6]
 [ 4]]
[ 6  7  8  9 10 11 12 13 14 15]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4]


In [5]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)
print(ndarray1)
print("=" * 30)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2)
print("=" * 30)

# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))
print(ndarray2)
print("=" * 30)

# 3 Dimension으로 변경
ndarray3 = ndarray2.reshape((4, 2, -1))
print(ndarray3)
print("=" * 30)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))
print(ndarray2)
print("=" * 30)

# ndarray3을 1 Dimension으로 변환
# flaten() : 1차원 배열로 만든다(평탄화) 
# ndarray1 = ndarray3.flatten()
ndarray1 = ndarray3.reshape(-1)
print(ndarray1)
print("=" * 30)

# 1차원 ndarray 1~100 까지 값 중 97값 추출하기
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1[-4])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
97


In [91]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4, 5))
print(ndarray2[2, 4])
print("=" * 30)

# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray1.reshape((5, -1))
print(ndarray2)
print("=" * 30)

# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])
print("=" * 30)

# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
Even = ndarray1[ndarray1 % 2 == 0]
print(Even)
print("=" * 50)

# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2 = Even.reshape((10, -1))
print(ndarray2[ndarray2 >= 82])
print("=" * 50)

# 위에서 구한 요소 중 (86, 100) 좌표 구하기
# ????

15
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
8
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 82  84  86  88  90  92  94  96  98 100]


In [6]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다
ndarray1 = np.arange(start=1, stop=101)

#각 요소 중 1의 자리수가 2인 수들만 추출하기
data = ndarray1[ndarray1 % 10 == 2]
print(data)
print("=" * 30)

# 1~49요소 중 2와 5의 공배수 추출하기
ndarray1 = np.arange(start=1, stop=50)
data = ndarray1[(ndarray1 % 2 == 0)&(ndarray1 % 5 == 0)]
print(data)
print("=" * 30)

# 위에서 추출한 공배수 중 20이상인 값만 추출하기
data = data[data >= 20]
print(data)
print("=" * 30)

# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = np.array([['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]])
print(array1[1])
sorted_array1 = array1[1].argsort()
print(array1[0][sorted_array1])
print(array1[0][sorted_array1][::-1])
print("=" * 30)

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = np.array([['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']])
name = array2[0]
age = array2[1].astype(np.int32)
grade = array2[2]

print("나이별 내림차순")
sorted_array2 = age.argsort()
print(name[sorted_array2][::-1], "\n")

print("학점별 오름차순")
sorted_array2 = grade.argsort()
print(name[sorted_array2])
print("=" * 30)

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = np.array([['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']])
nation = array3[0]
GDP = array3[1]

# for i, gdp in enumerate(array3[1]):
#     array3[1][i] = gdp.replace('%', '')
# GDP = array3[1].astype(np.float16)

print(GDP)
print(GDP.dtype)

sorted_GDP = GDP.argsort()
print(sorted_GDP)
print("GDP 성장률별 오름차순")
print(nation[sorted_GDP])
print("이게 왜 댐???")

[ 2 12 22 32 42 52 62 72 82 92]
[10 20 30 40]
[20 30 40]
['1500' '1800' '2000' '2500' '8500']
['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']
나이별 내림차순
['길동' '마이콜' '또치' '둘리' '도너'] 

학점별 오름차순
['또치' '길동' '둘리' '마이콜' '도너']
['1.7%' '-0.6%' '0.3%' '1.2%' '1.4%']
<U9
[1 2 3 4 0]
GDP 성장률별 오름차순
['영국' '러시아' '남아프리카 공화국' '미국' '한국']
이게 왜 댐???
